version: '3.8'

services:
  app:
    build: ./milk-quality-demo/
    command: sh -c "sleep 10s; streamlit run Main.py; echo RUN!"
    ports:
      - '7777:8501'
    depends_on:
      - mysql

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'milk_quality_prediction'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '5555:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: